name: eshop_app
description: E-Shop app is an E-Commerce application for all people around the world.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  dartz: ^0.10.1
  lottie: ^2.3.2
  get: ^4.6.5
  shared_preferences: ^2.1.0
  flutter_screenutil:
  cached_network_image: ^3.2.3
  animations: ^2.0.7
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.5
  intl: ^0.18.1
  data_table_2: ^2.4.2
  flutter_rating_bar: ^4.0.1
  flutter_advanced_segment: ^3.0.2
  image_picker: ^0.8.7+5
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/images/illustrations/
    - assets/images/items/
    - assets/images/people/
